variables:
  WEBHOOK_URL: $WEBHOOK_URL
  SERVICE_ID: $SERVICE_ID
  PATH_TO_PACKAGE_JSON_FILE: $PATH_TO_PACKAGE_JSON_FILE

stages:
  - build

ingest_packages_to_port_job:
  stage: build
  image: ubuntu:latest
  only:
    - main
    - dev
  before_script:
    - apt-get update
    - apt-get install -y curl jq
  script:
    - echo "Uploading Packages to Port"
    - sh ingest.sh