image: python:3.8

variables:
  WEBHOOK_URL: $WEBHOOK_URL
  SERVICE_ID: $SERVICE_ID
  PATH_TO_PACKAGE_JSON_FILE: $PATH_TO_PACKAGE_JSON_FILE

stages:
  - build

ingest_packages_to_port_job:
  stage: build
  before_script:
    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --no-cache-dir -r requirements.txt
  script:
    - echo "Uploading Packages to Port"
    - python ingest.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always